[project]
name = "samsolver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cpmpy>=0.9.28",
    "sympy>=1.14.0",
    "setuptools<80"
]
